import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { Trade, TradeConfig, Portfolio } from '../types';

/* 
  --- SQL SCHEMA FOR SUPABASE ---
  Run this in your Supabase SQL Editor to create the necessary tables:

  create table if not exists trades (
    id text primary key,
    asset text,
    side text,
    size numeric,
    entry_price numeric,
    pnl numeric,
    fees numeric,
    reasoning text,
    timestamp bigint,
    status text,
    exit_price numeric,
    market_snapshot jsonb
  );

  create table if not exists system_status (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    equity numeric,
    balance numeric,
    active_trades_count int,
    fear_index int,
    config jsonb
  );
*/

// Configuration
const SUPABASE_URL = 'https://hnwweqrmjrygvzbwyjig.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhud3dlcXJtanJ5Z3Z6Ynd5amlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMDMwODMsImV4cCI6MjA3OTU3OTA4M30.0VkrFUAFaNeXwnfdcKS2f3F21TFqRry-Lf_9sGVSCbw';

let supabase: SupabaseClient | null = null;
let dbConnected = false;
let tablesMissing = false; // Flag to prevent spamming errors if tables don't exist

if (SUPABASE_URL && SUPABASE_KEY) {
  try {
    supabase = createClient(SUPABASE_URL, SUPABASE_KEY);
    dbConnected = true;
    console.log("Supabase Client Initialized");
  } catch (e) {
    console.error("Supabase init failed", e);
  }
}

const handleSupabaseError = (error: any, context: string) => {
    // Check for "Undefined Table" error (Postgres code 42P01) or specific messages
    // 42P01 is the Postgres error code for undefined_table
    if (error.code === '42P01' || error.message?.includes('Could not find the table') || error.message?.includes('relation "public.trades" does not exist')) {
        if (!tablesMissing) {
            console.warn(`Supabase tables missing (${context}). Switching to Simulation Mode (No Persistence). Please run the SQL setup script provided in services/supabaseService.ts.`);
            tablesMissing = true;
        }
        return true; // Handled as missing table
    }
    console.error(`Supabase Error (${context}):`, error.message || error);
    return false;
};

export const logTrade = async (trade: Trade): Promise<void> => {
  if (!supabase || !dbConnected || tablesMissing) return;
  
  const dbRecord = {
      id: trade.id,
      asset: trade.asset,
      side: trade.side,
      size: trade.size,
      entry_price: trade.entryPrice,
      pnl: trade.pnl,
      fees: trade.fees,
      reasoning: trade.reasoning,
      timestamp: trade.timestamp,
      status: trade.status,
      exit_price: trade.exitPrice,
      market_snapshot: trade.marketSnapshot
  };

  const { error } = await supabase.from('trades').upsert([dbRecord]);
  if (error) handleSupabaseError(error, 'logTrade');
};

export const saveSystemStatus = async (portfolio: Portfolio, activeTradesCount: number, fearIndex: number, config: TradeConfig): Promise<void> => {
    if (!supabase || !dbConnected || tablesMissing) return;

    const { error } = await supabase.from('system_status').insert([{
        equity: portfolio.equity,
        balance: portfolio.balance,
        active_trades_count: activeTradesCount,
        fear_index: fearIndex,
        config: config
    }]);

    if (error) handleSupabaseError(error, 'saveSystemStatus');
};

export const fetchTradeHistory = async (): Promise<Trade[]> => {
  if (!supabase || !dbConnected || tablesMissing) return [];
  
  const { data, error } = await supabase
    .from('trades')
    .select('*')
    .order('timestamp', { ascending: false })
    .limit(50);
  
  if (error) {
    if (handleSupabaseError(error, 'fetchTradeHistory')) {
        return [];
    }
    return [];
  }
  
  if (!data) return [];

  // Map back to JS Interface
  return data.map((row: any) => ({
      id: row.id,
      asset: row.asset,
      side: row.side,
      size: row.size,
      entryPrice: row.entry_price,
      exitPrice: row.exit_price,
      pnl: row.pnl,
      fees: row.fees,
      timestamp: row.timestamp,
      status: row.status,
      reasoning: row.reasoning,
      aiConfidence: 0, 
      marketSnapshot: row.market_snapshot
  })) as Trade[];
};

export const saveConfig = async (config: TradeConfig): Promise<void> => {
   if (!supabase || !dbConnected || tablesMissing) return;
   // Optional implementation for saving config
};