
import { Trade, TradeConfig, Portfolio } from '../types';

export const sendTelegramMessage = async (message: string, config: TradeConfig) => {
    if (!config.notificationsEnabled || !config.telegramBotToken || !config.telegramChatId) return;

    const url = `https://api.telegram.org/bot${config.telegramBotToken}/sendMessage`;
    
    try {
        await fetch(url, {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({ 
                chat_id: config.telegramChatId, 
                text: message, 
                parse_mode: 'Markdown' 
            })
        });
    } catch (e) {
        console.error("Telegram Send Error", e);
    }
};

export const formatTradeMessage = (trade: Trade, isClose: boolean = false): string => {
    const icon = isClose 
        ? (trade.pnl && trade.pnl >= 0 ? '✅ *TRADE CLOSED - PROFIT*' : '🛑 *TRADE CLOSED - LOSS*')
        : (trade.side === 'LONG' ? '🚀 *OPEN LONG*' : '📉 *OPEN SHORT*');

    const pnlLine = isClose 
        ? `\n💰 **PnL:** ${trade.pnl && trade.pnl >= 0 ? '+' : ''}${trade.pnl?.toFixed(2)} USD` 
        : '';

    return `${icon}
    
**Asset:** ${trade.asset}
**Price:** $${trade.entryPrice.toFixed(2)}${isClose ? ` -> $${trade.exitPrice?.toFixed(2)}` : ''}
**Size:** $${trade.size.toFixed(2)} (${trade.leverage}x)
${pnlLine}
**Reason:** _${trade.reasoning}_

#NeuroLiquid #AI`;
};

export const formatPerformanceReport = (portfolio: Portfolio, trades: Trade[]): string => {
    const closedTrades = trades.filter(t => t.status === 'CLOSED');
    const wins = closedTrades.filter(t => (t.pnl || 0) > 0).length;
    const winRate = closedTrades.length > 0 ? (wins / closedTrades.length * 100).toFixed(1) : '0.0';
    const totalPnl = closedTrades.reduce((acc, t) => acc + (t.pnl || 0), 0);

    return `📊 *PERFORMANCE REPORT*

**Equity:** $${portfolio.equity.toFixed(2)}
**Total PnL:** $${totalPnl.toFixed(2)}
**Win Rate:** ${winRate}%
**Total Trades:** ${closedTrades.length}

_Generated by NeuroLiquid AI_`;
};
